### ISSUE TITLE
`XOR` swapping technique

### ISSUE THREAD

**Issue by Abdallah-Abdelrahman** [Abdallah-Abdelrahman/sorting_algorithms#1]
Swapping 2 elements in an array using `xor` is neat indeed! **_but_** it's not always save!
consider the following:

```c
int arr[] = {1, 2}, i = 0, j = i;
arr[i] ^= arr[j];
arr[j] ^= arr[i];
arr[i] ^= arr[j]; /* arr = {0, 2} */
```

**Comment by Mohabdo21** [comment]
I've used `xor` in selection_sort, no issues with random sets of integers and checker ✅ "some sort of luck"

you are right, the issue with bit manipulation raised when dealing with variables being swapped are the same, as it will result in zeroing out the variable just like your above example.
